### NumPy, or the Numeric Python library, is useful for working with arrays, which are data structures that store values of the same data type.
### NumPy arrays are similar to Python lists except that they require less memory and are usually faster because they use optimized, precompiled C code.
### Also supports element wise operations -> [1,2,3] + [3,2,1] = [4, 4, 4]

In [3]:
import numpy as np

In [4]:
jeff_salary = [2700, 3000, 3000]
nick_salary = [1000, 1200, 1400]
tom_salary = [2200, 3100, 3300]

base_salary = np.array([jeff_salary, nick_salary, tom_salary])
print(base_salary)

[[2700 3000 3000]
 [1000 1200 1400]
 [2200 3100 3300]]


In [5]:
jeff_bonus = [500,400,400]
nick_bonus = [600,300,400]
tom_bonus = [200,500,400]
bonus = np.array([jeff_bonus, nick_bonus, tom_bonus])

salary_bonus = base_salary + bonus
print(type(salary_bonus))
print(salary_bonus)

<class 'numpy.ndarray'>
[[3200 3400 3400]
 [1600 1500 1800]
 [2400 3600 3700]]


In [6]:
# Print max of the whole numpy array
print(salary_bonus.max())

3700


In [7]:
# find max in each horizontal axis (1) 
print(np.amax(salary_bonus, axis = 1))

[3400 1800 3700]


In [8]:
# find max in each vertical axis (0) 
print(np.amax(salary_bonus, axis = 0))

[3200 3600 3700]


In [9]:
# find median in each horizontal axis (1)
print(np.median(salary_bonus, axis = 1))

[3400. 1600. 3600.]


In [10]:
# find average in each horizontal axis (1)
print(np.average(salary_bonus, axis = 1))

[3333.33333333 1633.33333333 3233.33333333]
